"""initial

Revision ID: 764b5296652c
Revises: 
Create Date: 2026-04-19 11:29:59.522869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764b5296652c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('arr_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.alter_column('arr_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('client_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('downloads', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
